FROM python:3.11-slim

WORKDIR /app

COPY src/dashboard_node/requirements_dashboard.txt .

RUN pip install --default-timeout=1000 \
    --retries 10 \
    --no-cache-dir \
    -r requirements_dashboard.txt

COPY . /app

CMD ["python", "src/dashboard_node/dashboard_subscriber.py"]